# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_geigen <- function(A, B) {
    .Call('_CovTools_rcpp_geigen', PACKAGE = 'CovTools', A, B)
}

#' @keywords internal
#' @noRd
rcpp_ADMMprecision <- function(S, lambda) {
    .Call('_CovTools_rcpp_ADMMprecision', PACKAGE = 'CovTools', S, lambda)
}

rcpptest1_cai11 <- function(X) {
    .Call('_CovTools_rcpptest1_cai11', PACKAGE = 'CovTools', X)
}

