# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covest_2003LW_computeF <- function(S, rbar) {
    .Call('_CovTools_covest_2003LW_computeF', PACKAGE = 'CovTools', S, rbar)
}

covest_2003LW_computePi <- function(Y, Ybar, matS) {
    .Call('_CovTools_covest_2003LW_computePi', PACKAGE = 'CovTools', Y, Ybar, matS)
}

covest_2003LW_computeRho <- function(Y, Ybar, matS, rbar) {
    .Call('_CovTools_covest_2003LW_computeRho', PACKAGE = 'CovTools', Y, Ybar, matS, rbar)
}

rcpp_geigen <- function(A, B) {
    .Call('_CovTools_rcpp_geigen', PACKAGE = 'CovTools', A, B)
}

#' @keywords internal
#' @noRd
rcpp_ADMMprecision <- function(S, lambda) {
    .Call('_CovTools_rcpp_ADMMprecision', PACKAGE = 'CovTools', S, lambda)
}

rcpptest1_cai11 <- function(X) {
    .Call('_CovTools_rcpptest1_cai11', PACKAGE = 'CovTools', X)
}

